version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: edu-registry-db
    environment:
      POSTGRES_DB: edu_registry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - edu-registry-network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: edu-registry-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/edu_registry
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - edu-registry-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  edu-registry-network:
    driver: bridge