spring:
  application:
    name: edu-registry

  datasource:
    url: jdbc:postgresql://localhost:5432/edu_registry
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080

logging:
  level:
    com.shdwraze.eduregistry: DEBUG
    org.springframework.web: DEBUG